$atxcc.debug = {// debug.js
scope: {
    ctrlSupport: {
        id: 0,
        doCallback: 0,
    },
    _debug: {
        debug: 0,
        doDebug: 0,
        getName: 0,
    },
    elementsMake: {
        makeBaretext: 0,
        makeBr: 0,
        makeParagraph: 0,
        makeInput: 0,
        makeForm: 0,
        makeButton: 0,
        makeFieldset: 0,
        makeSelect: 0,
        makeFormContent: 0,
        makeTextArea: 0,
        makeTextAreaFit: 0,
        makeLabel: 0,
        makeImage: 0,
        makeDivSelf: 0,
        makeDiv: 0,
        makeDivAfter: 0,
        makeUnorderedList: 0,
        makeListItem: 0,
        makeTable: 0,
        makeRow: 0,
        defaultCellContent: 0,
        insertSection: 0,
        makeElement: 0,
        makeElementAfter: 0,
        doMakeElement: 0,
        setBoxProperties: 0,
        removeElement: 0,
        removeBoxProperties: 0,
        fitToBox: 0,
        doError: 0,
        getTagType: 0,
    },
    events: {
        mouseMove: 0,
        keyDown: 0,
        xmeRemove: 0,
        descrDisplay: 0,
        descrWordHoverClick: 0,
        wordSearchRegister: 0,
        keywordSearch: 0,
        keywordRegister: 0,
        agendaSearch: 0,
        doNotify: 0,
        keywordDoRegister: 0,
        insertAlerts: 0,
    },
    init: {
        init: 0,
    },
    Key: {
        initKeydown: 0,
        initKeyup: 0,
        ignoreKeyEvent: 0,
        listenKeyEvent: 0,
        cKeydown: 0,
        cKeyup: 0,
        getKeyDownCode: 0,
    },
    util: {
        initId: 0,
        genId: 0,
        dumpOb: 0,
        dumpObH: 0,
        cssDo: 0,
        clText: 0,
        sha1: 0,
    },
    viewInit: {
        initView: 0,
        initVBody: 0,
        initVHeader: 0,
        initVModelData: 0,
        initVCanvas: 0,
        clearVCanvas: 0,
        initTmp: 0,
    },
}

}  // $atxcc.debug
$atxcc.dg = $atxcc.debug
